export const SET_VISIBILITY = 'SET_VISIBILITY';
export const SET_PLAYER_PLAYLIST = 'SET_PLAYER_PLAYLIST';
export const CLEAR_PLAYER_PLAYLIST = 'CLEAR_PLAYER_PLAYLIST';
export const SET_NOW_PLAYING = 'SET_NOW_PLAYING';

export const GET_PLAYER_TRACK_REQUEST = 'GET_PLAYER_TRACK_REQUEST';
export const GET_PLAYER_TRACK_SUCCESS = 'GET_PLAYER_TRACK_SUCCESS';
export const GET_PLAYER_TRACK_FAIL = 'GET_PLAYER_TRACK_FAIL';

export const CLEAR_PLAYER_TRACK = 'CLEAR_PLAYER_TRACK';

export const SEND_COMMAND = 'SEND_COMMAND';
export const RECEIVE_COMMAND = 'RECEIVE_COMMAND';
