export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL';

export const GET_ROOM_REQUEST = 'GET_ROOM_REQUEST';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAIL = 'GET_ROOM_FAIL';

export const CLEAR_ROOMS = 'CLEAR_ROOMS';

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const UPDATE_ROOM = 'UPDATE_ROOM';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';

export const GET_ROOM_PLAYLIST_REQUEST = 'GET_ROOM_PLAYLIST_REQUEST';
export const GET_ROOM_PLAYLIST_SUCCESS = 'GET_ROOM_PLAYLIST_SUCCESS';
export const GET_ROOM_PLAYLIST_FAIL = 'GET_ROOM_PLAYLIST_FAIL';

export const USER_ENTERED_ROOM = 'USER_ENTERED_ROOM';
export const USER_EXITED_ROOM = 'USER_EXITED_ROOM';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const KICK_USER = 'KICK_USER';

export const SET_ROOM_NOW_PLAYING = 'SET_ROOM_NOW_PLAYING';
